
// Paginator 

const ROWS_PER_PAGE_CHANGED = 'ROWS_PER_PAGE_CHANGED';
const PAGE_SWITCHED = 'PAGE_SWITCHED';
const MAX_PAGE_NUMBER_CHANGED = 'MAX_PAGE_NUMBER_CHANGED';
const PAGE_SWITCHED_TO_FIRST = 'PAGE_SWITCHED_TO_FIRST';

// Order list

const FETCH_ORDERS_REQUSTED = 'FETCH_ORDERS_REQUSTED';
const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';

// Search panel

const SEARCH_VALUE_CHANGED = 'SEARCH_VALUE_CHANGED';

export {
  ROWS_PER_PAGE_CHANGED,
  PAGE_SWITCHED,
  FETCH_ORDERS_REQUSTED,
  FETCH_ORDERS_SUCCESS,
  FETCH_ORDERS_FAILURE,
  SEARCH_VALUE_CHANGED,
  MAX_PAGE_NUMBER_CHANGED,
  PAGE_SWITCHED_TO_FIRST
}