
// Paginator 

const ROWS_PER_PAGE_CHANGED = 'ROWS_PER_PAGE_CHANGED';
const PAGE_SWITCHED = 'PAGE_SWITCHED';

// Order list

const FETCH_ORDERS_REQUSTED = 'FETCH_ORDERS_REQUSTED';
const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';

export {
  ROWS_PER_PAGE_CHANGED,
  PAGE_SWITCHED,
  FETCH_ORDERS_REQUSTED,
  FETCH_ORDERS_SUCCESS,
  FETCH_ORDERS_FAILURE,
}